"""Centralized policy and model constants for FlowGuard."""

RISK_BASE_SCORE = 0.215
RISK_LOW_THRESHOLD = 0.34
RISK_HIGH_THRESHOLD = 0.66
RISK_CONFIDENCE_BASE = 0.82
RISK_CONFIDENCE_MIN = 0.55
RISK_CONFIDENCE_MAX = 0.95
RISK_CONFIDENCE_HISTORY_SCALE = 100
RISK_TREND_SCORES = {"DECLINING": -0.60, "STABLE": 0.0, "RISING": 0.35}
RISK_WEIGHTS = {
    "income_volatility": 0.34,
    "income_trend": 0.20,
    "expense_burden": 0.40,
    "low_buffer_coverage": -0.22,
    "debt_service_burden": 0.16,
    "income_gap": 0.22,
}

FORECAST_WEEKDAY_MULTIPLIERS = (1.08, 1.12, 1.05, 0.92, 0.96, 1.03, 1.10)
FORECAST_TREND_FACTOR = 0.15
FORECAST_DECLINE_SHOCK_BONUS = 0.22
FORECAST_BASE_SHOCK_PROBABILITY = 0.18
FORECAST_VOLATILITY_WEIGHT = 0.55
FORECAST_MAX_SHOCK_PROBABILITY = 0.95
FORECAST_MIN_SHOCK_PROBABILITY = 0.02
FORECAST_BAND_VOLATILITY_FACTOR = 0.35
FORECAST_MIN_BAND_FACTOR = 0.20
FORECAST_HORIZON_DAYS = 30
FORECAST_HISTORY_WINDOW_DAYS = 7
FORECAST_TREND_THRESHOLD = 0.08
FORECAST_DECLINING_TREND_SCORE = -0.35
FORECAST_RISING_TREND_SCORE = 0.20
FORECAST_MIN_DAILY_BAND_FACTOR = 0.20
FORECAST_WEATHER_STABLE_THRESHOLD = 0.35
FORECAST_WEATHER_SHOCK_THRESHOLD = 0.65

BUFFER_TARGET_DAYS = {"HIGH": 30, "MODERATE": 21, "LOW": 14}
SCORE_CAPS = {
    "income_stability": 25,
    "emergency_buffer": 25,
    "expense_coverage": 20,
    "debt_burden": 15,
    "savings_consistency": 15,
}
TOPUP_RATES = {"NORMAL": 0.10, "RECOVERY": 0.08, "WATCH": 0.06, "SHOCK": 0.0}
SHOCK_SPEND_FACTOR = 0.60
GROWTH_ALLOCATION_RATE = 0.05
RECOMMENDED_SAVE_DAYS = 20
CRITICAL_RESILIENCE_DAYS = 7
MIN_RECOMMENDATION_SAVE = 200

CREDIT_FUTURE_INCOME_RATE = 0.10
CREDIT_REPAYMENT_CAP_RATE = 0.25
CREDIT_MIN_SERVICE_RATE = 0.25

MONTH_DAYS = 30
OBLIGATION_INCOME_COVERAGE_RATE = 0.50
RECOVERY_BUFFER_RATIO = 0.30
SHOCK_DEFAULT_FACTOR = 0.65
SHOCK_PROBABILITY_INCREMENT = 0.30
SHOCK_RISK_INCREMENT = 0.25
SHOCK_SIMULATION_SPEND_FACTOR = 0.55
SHOCK_MAX_PROBABILITY = 0.95
SHOCK_MAX_RISK_SCORE = 0.95
RECOVERY_SHOCK_PROBABILITY_DECREMENT = 0.30
RECOVERY_RISK_DECREMENT = 0.20
RECOVERY_MIN_SHOCK_PROBABILITY = 0.15
RECOVERY_MIN_RISK_SCORE = 0.20
RECOVERY_SPEND_FACTOR = 1.40
RECOVERY_SCORE_INCREMENT = 10
