"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3, CreditCard, LayoutDashboard, Settings, ShieldCheck, WalletCards } from "lucide-react";
import { useScenario } from "./ScenarioProvider";
import type { Scenario } from "@/types/dashboard";

const links = [{ href: "/dashboard", label: "Dashboard", icon: LayoutDashboard }, { href: "/forecast", label: "Financial Forecast", icon: BarChart3 }, { href: "/resilience", label: "Resilience", icon: ShieldCheck }, { href: "/transactions", label: "Transactions", icon: WalletCards }, { href: "/credit", label: "Credit Guard", icon: CreditCard }];
export function Sidebar() { const pathname = usePathname(); const { scenario, setScenario } = useScenario(); return <aside className="hidden min-h-screen w-60 flex-col bg-[#103b2a] px-4 py-6 text-white lg:flex"><Link href="/dashboard" className="mb-12 flex items-center gap-3 px-2 text-xl font-extrabold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#35bb7a] text-[#103b2a]">↗</span>FlowGuard</Link><nav className="space-y-1">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${pathname === href ? "bg-white/10 text-white" : "text-[#b8d2c1] hover:bg-white/5 hover:text-white"}`}><Icon size={18} />{label}</Link>)}</nav><div className="mt-auto border-t border-white/15 pt-5"><label className="eyebrow block px-2 !text-[#a6c5b1]">Demo mode</label><select aria-label="Demo scenario" value={scenario} onChange={(event) => setScenario(event.target.value as Scenario)} className="mt-2 w-full rounded-lg border border-white/20 bg-[#0b3022] px-3 py-2 text-sm text-white"><option value="NORMAL">Normal</option><option value="INCOME_SHOCK">Income Shock</option><option value="RECOVERY">Recovery</option></select><Link href="/settings" className="mt-5 flex items-center gap-3 px-3 py-2 text-sm text-[#b8d2c1]"><Settings size={17} />Settings</Link></div></aside>; }
